-- ============================================================
-- VidGen: Videos Table Schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor)
--
-- One series can have MULTIPLE video records.
-- Each video record stores all assets generated in one run.
-- ============================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: videos
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS videos (
  -- Primary key
  id               BIGSERIAL      PRIMARY KEY,

  -- Relationship — one series → many videos
  series_id        BIGINT         NOT NULL REFERENCES series(id) ON DELETE CASCADE,

  -- Owner (Clerk user ID)
  user_id          TEXT           NOT NULL,

  -- ── STEP 2 output (script) ───────────────────────────────────────────────
  -- Short catchy video title generated by AI
  title            TEXT,

  -- Full concatenated voiceover script (all scene voiceovers joined)
  script           TEXT,

  -- ── STEP 3 output (TTS) ──────────────────────────────────────────────────
  -- Per-scene audio files stored in Supabase Storage
  -- Shape: [{ order: number, audioUrl: string }]
  audio_urls       JSONB          NOT NULL DEFAULT '[]'::jsonb,

  -- TTS provider used ("deepgram" | "fonadalab")
  tts_provider     TEXT,

  -- ── STEP 4 output (captions) ─────────────────────────────────────────────
  -- Full merged SRT caption string for the entire video
  captions_srt     TEXT,

  -- Per-scene word-level caption data (for caption overlay rendering)
  -- Shape: [{ order: number, srt: string, words: [{ word, start, end }] }]
  captions_scenes  JSONB          NOT NULL DEFAULT '[]'::jsonb,

  -- ── STEP 5 output (images) ───────────────────────────────────────────────
  -- Per-scene generated images stored in Supabase Storage
  -- Shape: [{ order: number, prompt: string, imageUrl: string }]
  images           JSONB          NOT NULL DEFAULT '[]'::jsonb,

  -- ── STEP 7 output (rendered video) ──────────────────────────────────────
  -- Final MP4 public URL in Supabase Storage (set after Remotion renders)
  video_url        TEXT,

  -- ── Generation status ────────────────────────────────────────────────────
  -- pending | generating | completed | failed
  status           TEXT           NOT NULL DEFAULT 'pending',

  -- Optional error message if status = 'failed'
  error_message    TEXT,

  -- ── Email notification tracking ──────────────────────────────────────────
  -- Whether completion email was successfully sent
  email_sent       BOOLEAN        DEFAULT NULL,

  -- Timestamp when email was sent
  email_sent_at    TIMESTAMPTZ,

  -- Error message if email sending failed
  email_error      TEXT,

  -- Timestamps
  created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

-- ⚠️  If the videos table ALREADY EXISTS, run these lines separately:
ALTER TABLE IF EXISTS videos ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE IF EXISTS videos ADD COLUMN IF NOT EXISTS email_sent BOOLEAN DEFAULT NULL;
ALTER TABLE IF EXISTS videos ADD COLUMN IF NOT EXISTS email_sent_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS videos ADD COLUMN IF NOT EXISTS email_error TEXT;



-- ─────────────────────────────────────────────────────────────────────────────
-- AUTO-UPDATE updated_at on every row change
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER videos_updated_at
  BEFORE UPDATE ON videos
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ─────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- ─────────────────────────────────────────────────────────────────────────────
-- Fetch all videos for a series (most common query)
CREATE INDEX IF NOT EXISTS idx_videos_series_id ON videos(series_id);

-- Fetch all videos for a user
CREATE INDEX IF NOT EXISTS idx_videos_user_id   ON videos(user_id);

-- Filter by status quickly
CREATE INDEX IF NOT EXISTS idx_videos_status    ON videos(status);

-- Compound index for dashboard: user + series
CREATE INDEX IF NOT EXISTS idx_videos_user_series ON videos(user_id, series_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;

-- Regular users only see their own videos
CREATE POLICY "Users can view own videos"
  ON videos FOR SELECT
  USING (auth.uid()::text = user_id);

-- Service role key (used by Inngest functions) bypasses RLS
-- This relies on Supabase's built-in service role bypass.
-- If you need explicit RLS for service role:
-- CREATE POLICY "Service role full access"
--   ON videos FOR ALL
--   USING (TRUE) WITH CHECK (TRUE);
